apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app
          image: py-app:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              